services:
  postgres:
    extends:
      file: services.yml
      service: postgres
    env_file:
      - .env
    networks:
      - default
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    extends:
      file: services.yml
      service: redis
    networks:
      - default

  hono-app:
    extends:
      file: services.yml
      service: hono-app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - default

volumes:
  pg_data:

networks:
  default:
    driver: bridge
    