services:
  hono-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/seorangabi-api/uploads:/app/uploads

  # Postgres
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]