services:
  hono-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono
    ports:
      - "3020:3020"
    volumes:
      - ./uploads:/app/uploads

  # Postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ~/apps/redis:/data
    command: ["redis-server", "--appendonly", "yes", "--replica-read-only", "no"]